import { ExternalLink, Mail } from "lucide-react";

export function Footer() {
  return (
    <footer className="border-t border-surface-700/50 bg-surface-900">
      <div className="mx-auto max-w-6xl px-6 py-12">
        <div className="flex flex-col md:flex-row items-center justify-between gap-6">
          <div className="text-center md:text-left">
            <p className="text-sm text-surface-200">
              Built with AI. Not generated by AI.
            </p>
            <p className="text-xs text-surface-200/50 mt-1">
              Every system on this site was architected, debugged, and shipped
              — AI accelerated the execution, not the thinking.
            </p>
          </div>

          <div className="flex items-center gap-4">
            <a
              href="https://github.com/canfieldjuan/atlas-portfolio"
              target="_blank"
              rel="noopener noreferrer"
              className="text-surface-200/60 hover:text-primary-400 transition-colors flex items-center gap-1.5 text-sm"
              aria-label="GitHub"
            >
              <ExternalLink size={14} />
              GitHub
            </a>
            <a
              href="https://www.linkedin.com/in/juan-canfield-9b2a733b5/"
              target="_blank"
              rel="noopener noreferrer"
              className="text-surface-200/60 hover:text-primary-400 transition-colors flex items-center gap-1.5 text-sm"
              aria-label="LinkedIn"
            >
              <ExternalLink size={14} />
              LinkedIn
            </a>
            <a
              href="mailto:campfieldjuan24@gmail.com"
              className="text-surface-200/60 hover:text-primary-400 transition-colors flex items-center gap-1.5 text-sm"
              aria-label="Email"
            >
              <Mail size={14} />
              Contact
            </a>
          </div>
        </div>
      </div>
    </footer>
  );
}
