#!/usr/bin/env python3
"""Scan atlas_brain/ for all direct b2b_reviews.enrichment JSONB reads.

Produces docs/B2B_FIELD_ACCESS_INVENTORY_<date>.md with:
  - Every file that reads enrichment-> or enrichment->>
  - The specific field names accessed
  - Line numbers and SQL fragments
  - Grouped by file, sorted by read count descending

Usage:
    python scripts/b2b_field_access_inventory.py
"""

from __future__ import annotations

import re
import sys
from collections import defaultdict
from datetime import date
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(REPO_ROOT))
SCAN_ROOTS = [REPO_ROOT / "atlas_brain", REPO_ROOT / "scripts"]
OUTPUT_DIR = REPO_ROOT / "docs"

# Matches enrichment->>'field', enrichment->'field', and enrichment #>> '{field,...}'
ENRICHMENT_RE = re.compile(
    r"""(?:\w+\.)?enrichment\s*->>?\s*'([^']+)'"""
    r"""|(?:\w+\.)?enrichment\s*#>>?\s*'\{([^,}]+)""",
    re.IGNORECASE,
)

# Matches nested access: enrichment->'obj'->>'nested'
ENRICHMENT_NESTED_RE = re.compile(
    r"""(?:\w+\.)?enrichment\s*->\s*'([^']+)'\s*->>?\s*'([^']+)'"""
    r"""|(?:\w+\.)?enrichment\s*#>>?\s*'\{([^,}]+),([^,}]+)""",
    re.IGNORECASE,
)

def _is_exempt(rel_path: str) -> bool:
    """Mirror the exemption logic in test_b2b_field_governance.py."""
    from atlas_brain.autonomous.tasks._b2b_field_contracts import EXEMPT_MODULES
    if rel_path in EXEMPT_MODULES:
        return True
    if rel_path.startswith("scripts/backfill_") or rel_path.startswith("scripts/re_enrich_"):
        return True
    return False


def scan_file(path: Path) -> list[dict]:
    """Return list of enrichment read hits in a single file."""
    hits = []
    try:
        lines = path.read_text(encoding="utf-8", errors="replace").splitlines()
    except Exception:
        return hits

    for lineno, line in enumerate(lines, 1):
        # Top-level field access (-> / ->> and #> / #>> forms)
        for m in ENRICHMENT_RE.finditer(line):
            field = m.group(1) or m.group(2)
            if not field:
                continue
            hits.append({
                "field": field,
                "nested": None,
                "line": lineno,
                "fragment": line.strip()[:120],
            })

        # Nested field access (overrides top-level for same match)
        for m in ENRICHMENT_NESTED_RE.finditer(line):
            parent = m.group(1) or m.group(3)
            child = m.group(2) or m.group(4)
            # Find and update the top-level hit for this parent
            updated = False
            for h in hits:
                if h["line"] == lineno and h["field"] == parent and h["nested"] is None:
                    h["nested"] = child
                    updated = True
                    break
            if not updated:
                hits.append({
                    "field": parent,
                    "nested": child,
                    "line": lineno,
                    "fragment": line.strip()[:120],
                })

    return hits


def relative(path: Path) -> str:
    return str(path.relative_to(REPO_ROOT))


def main():
    all_files: dict[str, list[dict]] = {}
    field_totals: dict[str, int] = defaultdict(int)
    nested_totals: dict[str, int] = defaultdict(int)

    for scan_root in SCAN_ROOTS:
        for pyfile in sorted(scan_root.rglob("*.py")):
            hits = scan_file(pyfile)
            if not hits:
                continue
            rel = relative(pyfile)
            all_files[rel] = hits
            for h in hits:
                field_totals[h["field"]] += 1
                if h["nested"]:
                    nested_totals[f"{h['field']}.{h['nested']}"] += 1

    today = date.today().isoformat()
    out = OUTPUT_DIR / f"B2B_FIELD_ACCESS_INVENTORY_{today}.md"

    exempt_count = 0
    non_exempt_count = 0
    for rel, hits in all_files.items():
        if _is_exempt(rel):
            exempt_count += len(hits)
        else:
            non_exempt_count += len(hits)

    lines = [
        f"# B2B Enrichment Field Access Inventory ({today})",
        "",
        "Auto-generated by `scripts/b2b_field_access_inventory.py`.",
        "",
        "## Summary",
        "",
        f"- **Total files with enrichment reads**: {len(all_files)}",
        f"- **Total read sites**: {sum(len(h) for h in all_files.values())}",
        f"- **Reads in exempt modules**: {exempt_count}",
        f"- **Reads in non-exempt modules (ad-hoc)**: {non_exempt_count}",
        f"- **Unique top-level fields accessed**: {len(field_totals)}",
        "",
        "## Top-Level Field Frequency",
        "",
        "| Field | Total Reads |",
        "|-------|------------|",
    ]

    for field, count in sorted(field_totals.items(), key=lambda x: -x[1]):
        lines.append(f"| `{field}` | {count} |")

    if nested_totals:
        lines.extend([
            "",
            "## Nested Field Frequency",
            "",
            "| Field Path | Total Reads |",
            "|-----------|------------|",
        ])
        for path, count in sorted(nested_totals.items(), key=lambda x: -x[1]):
            lines.append(f"| `{path}` | {count} |")

    lines.extend(["", "## Reads by File", ""])

    for rel in sorted(all_files, key=lambda r: -len(all_files[r])):
        hits = all_files[rel]
        is_exempt = _is_exempt(rel)
        status = "EXEMPT" if is_exempt else "NON-EXEMPT"
        lines.append(f"### `{rel}` ({len(hits)} reads) [{status}]")
        lines.append("")
        lines.append("| Line | Field | Nested | Fragment |")
        lines.append("|------|-------|--------|----------|")
        for h in sorted(hits, key=lambda x: x["line"]):
            nested = h["nested"] or ""
            frag = h["fragment"].replace("|", "\\|")
            lines.append(f"| {h['line']} | `{h['field']}` | {nested} | `{frag}` |")
        lines.append("")

    out.write_text("\n".join(lines), encoding="utf-8")
    print(f"Inventory written to {out}")
    print(f"  {len(all_files)} files, {sum(len(h) for h in all_files.values())} read sites")
    print(f"  {exempt_count} exempt, {non_exempt_count} non-exempt")
    return 0


if __name__ == "__main__":
    sys.exit(main())
