#!/usr/bin/env python3
"""Compile one marker-aware lock from the Python 3.10/3.11 root+ASR graphs."""

from __future__ import annotations

import argparse
import hashlib
import re
import subprocess
import tempfile
from pathlib import Path


ROOT = Path(__file__).resolve().parent.parent
CONSTRAINTS_NAME = "constraints.root-asr.txt"
DIGEST_PREFIX = "# constraints-root-asr-sha256: "
INCLUDE_LINE = f"-c {CONSTRAINTS_NAME}"
UV_VERSION = "0.10.10"
PLATFORM = "x86_64-manylinux_2_28"
EXCLUDE_NEWER = "2026-07-14T19:30:00Z"
_NAME_RE = re.compile(r"^([A-Za-z0-9_.-]+)(?:\[[^]]+\])?")
_CONCRETE_RE = re.compile(
    r"^[A-Za-z0-9_.-]+(?:\[[^]]+\])?(?:==[^ ;]+| @ \S+)$"
)


def _normalized_name(line: str) -> str:
    match = _NAME_RE.match(line)
    if match is None:
        raise ValueError(f"cannot parse resolved project name: {line!r}")
    return re.sub(r"[-_.]+", "-", match.group(1)).lower()


def parse_resolution(text: str) -> dict[str, str]:
    """Parse uv's concrete, marker-free output into normalized project cells."""
    result: dict[str, str] = {}
    for raw_line in text.splitlines():
        line = raw_line.strip()
        if not line or line.startswith("#"):
            continue
        if not _CONCRETE_RE.fullmatch(line):
            raise ValueError(f"expected concrete resolver output, got {line!r}")
        name = _normalized_name(line)
        if name in result:
            raise ValueError(f"duplicate resolver cell for {name!r}")
        result[name] = line
    return result


def merge_resolutions(py310: dict[str, str], py311: dict[str, str]) -> list[str]:
    """Merge two concrete graphs into complete, non-overlapping marker cells."""
    merged: list[str] = []
    for name in sorted(py310.keys() | py311.keys()):
        line310 = py310.get(name)
        line311 = py311.get(name)
        if line310 == line311:
            if line310 is None:
                raise RuntimeError(f"resolver union lost project {name!r}")
            merged.append(line310)
            continue
        if line310 is not None:
            merged.append(f"{line310} ; python_version < '3.11'")
        if line311 is not None:
            merged.append(f"{line311} ; python_version >= '3.11'")
    return merged


def _without_lock_binding(path: Path) -> str:
    kept = [
        line
        for line in path.read_text(encoding="utf-8").splitlines()
        if line.strip() != INCLUDE_LINE and not line.startswith(DIGEST_PREFIX)
    ]
    return "\n".join(kept).lstrip("\n") + "\n"


def _uv_resolution(uv: str, python_version: str, directory: Path) -> str:
    root_input = directory / "requirements.root.txt"
    asr_input = directory / "requirements.asr.txt"
    output = directory / f"resolved-{python_version}.txt"
    root_input.write_text(
        _without_lock_binding(ROOT / "requirements.txt"), encoding="utf-8"
    )
    asr_input.write_text(
        _without_lock_binding(ROOT / "requirements.asr.txt"), encoding="utf-8"
    )
    command = [
        uv,
        "pip",
        "compile",
        str(root_input),
        str(asr_input),
        "--python-version",
        python_version,
        "--python-platform",
        PLATFORM,
        "--exclude-newer",
        EXCLUDE_NEWER,
        "--no-header",
        "--no-annotate",
        "--output-file",
        str(output),
    ]
    completed = subprocess.run(
        command, text=True, capture_output=True, check=False
    )
    if completed.returncode:
        raise RuntimeError(completed.stderr.strip() or completed.stdout.strip())
    return output.read_text(encoding="utf-8")


def compile_lock(uv: str) -> bytes:
    version = subprocess.run(
        [uv, "--version"], text=True, capture_output=True, check=True
    ).stdout.strip()
    if version != f"uv {UV_VERSION}":
        raise RuntimeError(f"expected uv {UV_VERSION}, got {version!r}")
    with tempfile.TemporaryDirectory(prefix="atlas-root-asr-lock-") as raw_dir:
        directory = Path(raw_dir)
        py310 = parse_resolution(_uv_resolution(uv, "3.10", directory))
        py311 = parse_resolution(_uv_resolution(uv, "3.11", directory))
    lines = [
        "# Generated by scripts/compile_root_asr_constraints.py; do not edit.",
        f"# Resolver: uv {UV_VERSION}; target: {PLATFORM}; Python: 3.10 + 3.11.",
        f"# Package upload cutoff: {EXCLUDE_NEWER}.",
        "# Regenerate: python scripts/compile_root_asr_constraints.py",
        "",
        *merge_resolutions(py310, py311),
    ]
    return ("\n".join(lines) + "\n").encode("utf-8")


def _bound_requirements(path: Path, digest: str | None) -> str:
    body = _without_lock_binding(path)
    prefix = [INCLUDE_LINE]
    if digest is not None:
        prefix.insert(0, f"{DIGEST_PREFIX}{digest}")
    return "\n".join(prefix) + "\n\n" + body


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    parser.add_argument("--uv", default="uv")
    args = parser.parse_args()

    expected = compile_lock(args.uv)
    digest = hashlib.sha256(expected).hexdigest()
    expected_root = _bound_requirements(ROOT / "requirements.txt", digest)
    expected_asr = _bound_requirements(ROOT / "requirements.asr.txt", None)
    constraints = ROOT / CONSTRAINTS_NAME

    if args.check:
        stale = []
        if not constraints.exists() or constraints.read_bytes() != expected:
            stale.append(CONSTRAINTS_NAME)
        if (
            ROOT / "requirements.txt"
        ).read_text(encoding="utf-8") != expected_root:
            stale.append("requirements.txt")
        if (
            ROOT / "requirements.asr.txt"
        ).read_text(encoding="utf-8") != expected_asr:
            stale.append("requirements.asr.txt")
        if stale:
            raise SystemExit(f"stale root/ASR lock files: {', '.join(stale)}")
        print(f"root/ASR constraints are current: {digest}")
        return 0

    constraints.write_bytes(expected)
    (ROOT / "requirements.txt").write_text(expected_root, encoding="utf-8")
    (ROOT / "requirements.asr.txt").write_text(expected_asr, encoding="utf-8")
    print(f"wrote {CONSTRAINTS_NAME}: {digest}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
