#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT_DIR"

bash scripts/validate_extracted_content_pipeline.sh
bash scripts/check_ascii_python.sh
python scripts/check_extracted_imports.py
python extracted/_shared/scripts/forbid_atlas_reasoning_imports.py extracted_content_pipeline
python scripts/smoke_extracted_pipeline_imports.py
python scripts/smoke_extracted_pipeline_standalone.py
python scripts/audit_extracted_standalone.py --fail-on-debt
bash scripts/run_extracted_reasoning_core_checks.sh
pytest \
  tests/test_extracted_campaign_analytics.py \
  tests/test_extracted_campaign_install_check.py \
  tests/test_extracted_content_host_smoke.py \
  tests/test_extracted_campaign_visibility.py \
  tests/test_extracted_campaign_visibility_reader_cli.py \
  tests/test_extracted_campaign_manifest.py \
  tests/test_extracted_campaign_generation_seams.py \
  tests/test_extracted_campaign_generation.py \
  tests/test_extracted_campaign_reasoning_data.py \
  tests/test_extracted_campaign_skill_registry.py \
  tests/test_extracted_campaign_generation_example.py \
  tests/test_extracted_campaign_customer_data.py \
  tests/test_extracted_campaign_source_adapters.py \
  tests/test_content_ops_faq_saas_demo_corpus.py \
  tests/test_content_ops_faq_report_contract_docs.py \
  tests/test_content_ops_deflection_report.py \
  tests/test_extracted_content_deflection_submit.py \
  tests/test_prepare_content_ops_deflection_env.py \
  tests/test_smoke_content_ops_deflection_submit_handoff.py \
  tests/test_extracted_ticket_faq_markdown.py \
  tests/test_extracted_ticket_faq_macro_writeback.py \
  tests/test_extracted_ticket_faq_macro_writeback_postgres.py \
  tests/test_extracted_ticket_faq_macro_writeback_publish.py \
  tests/test_extracted_ticket_faq_macro_writeback_reconcile_cli.py \
  tests/test_extracted_ticket_faq_macro_writeback_zendesk.py \
  tests/test_extracted_ticket_faq_output_ingestion.py \
  tests/test_smoke_content_ops_faq_output_proof.py \
  tests/test_smoke_content_ops_faq_search_concurrency.py \
  tests/test_smoke_content_ops_faq_search_route_concurrency.py \
  tests/test_smoke_content_ops_faq_search_seeded_route_e2e.py \
  tests/test_smoke_content_ops_faq_saas_demo_route_e2e.py \
  tests/test_check_content_ops_faq_search_route_contract.py \
  tests/test_evaluate_support_ticket_generated_content.py \
  tests/test_support_ticket_saas_demo_generated_content_fixtures.py \
  tests/test_smoke_content_ops_faq_scale_run.py \
  tests/test_smoke_content_ops_faq_lifecycle.py \
  tests/test_smoke_content_ops_faq_lifecycle_run.py \
  tests/test_smoke_content_ops_ingestion_file_route.py \
  tests/test_smoke_content_ops_ingestion_file_route_inprocess_load.py \
  tests/test_smoke_content_ops_ingestion_file_route_multiprocess_load.py \
  tests/test_smoke_content_ops_live_generation.py \
  tests/test_smoke_content_ops_review_source_generation.py \
  tests/test_export_content_ops_review_sources.py \
  tests/test_export_content_ops_cfpb_sources.py \
  tests/test_smoke_content_ops_cfpb_faq_markdown.py \
  tests/test_content_ops_source_postgres_smoke_helpers.py \
  tests/test_smoke_content_ops_source_file_postgres.py \
  tests/test_smoke_content_ops_review_source_postgres.py \
  tests/test_smoke_content_ops_cfpb_source_postgres.py \
  tests/test_extracted_content_ingestion_diagnostics.py \
  tests/test_extracted_blog_generation.py \
  tests/test_extracted_blog_blueprint_ingest.py \
  tests/test_extracted_blog_blueprint_postgres.py \
  tests/test_extracted_blog_post_postgres.py \
  tests/test_extracted_campaign_reasoning_postgres.py \
  tests/test_extracted_campaign_reasoning_cleanup_cli.py \
  tests/test_extracted_campaign_reasoning_upsert_cli.py \
  tests/test_extracted_campaign_reasoning_list_cli.py \
  tests/test_extracted_campaign_reasoning_postgres_check.py \
  tests/test_extracted_content_control_surfaces.py \
  tests/test_extracted_content_generation_plan.py \
  tests/test_extracted_content_reasoning_policy.py \
  tests/test_extracted_content_ops_cache_policy.py \
  tests/test_extracted_content_ops_input_provider.py \
  tests/test_support_ticket_context_contract.py \
  tests/test_extracted_support_ticket_input_package.py \
  tests/test_extracted_support_ticket_input_provider.py \
  tests/test_smoke_content_ops_support_ticket_package.py \
  tests/test_extracted_content_control_surface_api.py \
  tests/test_extracted_content_ops_usage_summary.py \
  tests/test_extracted_content_ops_execution.py \
  tests/test_extracted_content_ops_execution_smoke.py \
  tests/test_atlas_content_ops_infrastructure.py \
  tests/test_atlas_content_ops_generated_assets_api.py \
  tests/test_atlas_content_ops_import_admission.py \
  tests/test_atlas_content_ops_input_provider.py \
  tests/test_atlas_content_ops_macro_writeback.py \
  tests/test_content_ops_faq_macro_writeback_flow.py \
  tests/test_content_ops_zendesk_credentials.py \
  tests/test_content_ops_zendesk_credentials_api.py \
  tests/test_atlas_content_ops_reasoning.py \
  tests/test_atlas_content_ops_scope.py \
  tests/test_support_ticket_provider_landing_blog_execute.py \
  tests/test_atlas_content_ops_execution_services.py \
  tests/test_extracted_content_ops_live_execute_harness.py \
  tests/test_extracted_parse_retry_helpers.py \
  tests/test_extracted_report_postgres.py \
  tests/test_extracted_report_generation.py \
  tests/test_extracted_quality_gate_report_pack.py \
  tests/test_extracted_landing_page_postgres.py \
  tests/test_extracted_landing_page_generation.py \
  tests/test_extracted_landing_page_generation_smoke.py \
  tests/test_extracted_quality_gate_landing_page_pack.py \
  tests/test_extracted_sales_brief_postgres.py \
  tests/test_extracted_sales_brief_generation.py \
  tests/test_extracted_quality_gate_sales_brief_pack.py \
  tests/test_extracted_storage_jsonb_helpers.py \
  tests/test_extracted_campaign_postgres_generation.py \
  tests/test_extracted_campaign_postgres_export.py \
  tests/test_extracted_content_asset_export_cli.py \
  tests/test_extracted_content_asset_review_cli.py \
  tests/test_extracted_report_export.py \
  tests/test_extracted_blog_post_export.py \
  tests/test_extracted_landing_page_export.py \
  tests/test_extracted_sales_brief_export.py \
  tests/test_extracted_ticket_faq_export.py \
  tests/test_extracted_ticket_faq_postgres.py \
  tests/test_extracted_ticket_faq_search.py \
  tests/test_extracted_ticket_faq_search_api.py \
  tests/test_extracted_ticket_faq_search_postgres.py \
  tests/test_extracted_campaign_postgres_review.py \
  tests/test_extracted_campaign_postgres_seller_targets.py \
  tests/test_extracted_campaign_postgres_seller_opportunities.py \
  tests/test_extracted_campaign_postgres_seller_category_intelligence.py \
  tests/test_extracted_campaign_postgres_send.py \
  tests/test_extracted_campaign_postgres_analytics.py \
  tests/test_extracted_campaign_postgres_webhooks.py \
  tests/test_extracted_campaign_api_webhooks.py \
  tests/test_extracted_campaign_api_operations.py \
  tests/test_extracted_campaign_api_hosted_workflow.py \
  tests/test_extracted_content_asset_api.py \
  tests/test_extracted_campaign_api_b2b_campaigns.py \
  tests/test_extracted_campaign_api_seller_campaigns.py \
  tests/test_extracted_campaign_postgres_sequence_progression.py \
  tests/test_extracted_campaign_postgres_import.py \
  tests/test_extracted_campaign_port_taxonomy.py \
  tests/test_extracted_campaign_reasoning_context_api.py \
  tests/test_extracted_campaign_single_pass_reasoning.py \
  tests/test_extracted_campaign_multi_pass_reasoning_provider.py \
  tests/test_extracted_content_pipeline_migration_runner.py \
  tests/test_audit_extracted_pipeline_ci_enrollment.py \
  tests/test_extracted_pipeline_route_ci_contract.py \
  tests/test_extracted_pipeline_notify.py \
  tests/test_extracted_content_pipeline_reasoning_archetypes.py \
  tests/test_extracted_content_pipeline_reasoning_temporal.py \
  tests/test_extracted_content_pipeline_reasoning_evidence_engine.py \
  tests/test_atlas_reasoning_state_inherits_core.py \
  tests/test_atlas_reasoning_port_adapters.py \
  tests/test_atlas_reasoning_vendor_pressure.py \
  tests/test_atlas_reasoning_call_transcript.py \
  tests/test_atlas_reasoning_agent_port_consumption.py \
  tests/test_atlas_reasoning_reflection_tracing.py \
  tests/test_atlas_reasoning_graph_aliases.py \
  tests/test_atlas_reasoning_run_reasoning_graph_wiring.py \
  tests/test_atlas_reasoning_tiers_aliases.py \
  tests/test_atlas_reasoning_wedge_registry_aliases.py \
  tests/test_atlas_reasoning_temporal_aliases.py \
  tests/test_atlas_reasoning_archetypes_aliases.py \
  tests/test_atlas_reasoning_evidence_engine_aliases.py \
  tests/test_extracted_product_utilities.py \
  tests/test_extracted_b2b_batch_utils.py \
  tests/test_extracted_blog_matching.py \
  tests/test_extracted_campaign_audit.py \
  tests/test_extracted_campaign_llm_client.py \
  tests/test_extracted_campaign_llm_bridge.py \
  tests/test_extracted_vendor_briefing_seams.py \
  tests/test_extracted_campaign_postgres.py \
  tests/test_extracted_campaign_suppression.py \
  tests/test_extracted_campaign_sequence_context.py \
  tests/test_extracted_campaign_sequence_progression.py \
  tests/test_extracted_campaign_sender.py \
  tests/test_extracted_campaign_send.py \
  tests/test_extracted_campaign_webhooks.py \
  tests/test_extracted_podcast_transcript_import.py \
  tests/test_extracted_podcast_extraction.py \
  tests/test_extracted_podcast_repurpose_generation.py \
  tests/test_extracted_podcast_quality.py

echo "All extracted_content_pipeline checks completed"
